-- ====================================================
-- SUPABASE / POSTGRESQL SCHEMA AND DATA EXPORT
-- Includes full schema & actual wells, casings, tubings data
-- ====================================================

-- 1. Employees Table
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule TEXT,
    nom_prenom TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    password TEXT,
    d_rec TEXT,
    d_f_contrat TEXT,
    personnel TEXT,
    fonction TEXT,
    observation TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    t_combinaison TEXT,
    t_blouson TEXT,
    t_pantalon TEXT,
    t_parka TEXT,
    t_pantalon_ord TEXT,
    t_chemise_ord TEXT,
    t_tshirt_ord TEXT,
    t_pull TEXT,
    p_chaussure TEXT,
    t_veste_cuire TEXT,
    service TEXT
);

-- 2. Wells Table
CREATE TABLE IF NOT EXISTS public.wells (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    purpose TEXT DEFAULT 'Oil Producer',
    completion_type TEXT DEFAULT 'COMPLETION SIMPLE',
    reservoir TEXT,
    field TEXT,
    elevation_sol DOUBLE PRECISION DEFAULT 0,
    elevation_forage DOUBLE PRECISION DEFAULT 0,
    elevation_production DOUBLE PRECISION DEFAULT 0,
    spool_prod TEXT,
    packer_type TEXT,
    susp_tbg TEXT,
    etan_tbg TEXT,
    origine_cotes TEXT,
    xmas_tree_brand TEXT,
    xmas_tree_type TEXT,
    xmas_tree_ract_sup TEXT,
    xmas_tree_pressure TEXT,
    xmas_tree_attache_tbg TEXT,
    xmas_tree_embase TEXT,
    xmas_tree_reduction TEXT,
    xmas_tree_olive TEXT,
    vannes_sas_marque TEXT,
    vannes_sas_nombre TEXT,
    vannes_sas_serie TEXT,
    vannes_maitresse_marque TEXT,
    vannes_maitresse_nombre TEXT,
    vannes_maitresse_serie TEXT,
    vannes_lat_tbg_marque TEXT,
    vannes_lat_tbg_nombre TEXT,
    vannes_lat_tbg_serie TEXT,
    vannes_lat_csg_marque TEXT,
    vannes_lat_csg_nombre TEXT,
    vannes_lat_csg_serie TEXT,
    observations TEXT,
    folio TEXT,
    folio_to_cancel TEXT,
    prod_tbg_od TEXT,
    prod_tbg_grade TEXT,
    prod_tbg_weight TEXT,
    updated_date TEXT,
    end_operation_date TEXT,
    vu_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Casing Strings Table
CREATE TABLE IF NOT EXISTS public.casing_strings (
    id TEXT PRIMARY KEY,
    well_id TEXT NOT NULL REFERENCES public.wells(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    borehole_size TEXT NOT NULL,
    casing_size TEXT NOT NULL,
    top_depth DOUBLE PRECISION NOT NULL DEFAULT 0,
    shoe_depth DOUBLE PRECISION NOT NULL,
    drilled_depth DOUBLE PRECISION NOT NULL,
    top_of_cement DOUBLE PRECISION,
    top_of_liner DOUBLE PRECISION,
    top_of_fonde DOUBLE PRECISION,
    grade TEXT,
    weight DOUBLE PRECISION,
    connection TEXT,
    observations TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tubing Components Table
CREATE TABLE IF NOT EXISTS public.tubing_components (
    id TEXT PRIMARY KEY,
    well_id TEXT NOT NULL REFERENCES public.wells(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'Tubing',
    od TEXT NOT NULL,
    length DOUBLE PRECISION NOT NULL,
    bottom_depth DOUBLE PRECISION NOT NULL,
    is_cote_product_added BOOLEAN DEFAULT FALSE,
    observations TEXT,
    qty TEXT,
    custom_type TEXT,
    min_id TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Perforation Zones Table
CREATE TABLE IF NOT EXISTS public.perforation_zones (
    id TEXT PRIMARY KEY,
    well_id TEXT NOT NULL REFERENCES public.wells(id) ON DELETE CASCADE,
    top_depth DOUBLE PRECISION NOT NULL,
    bottom_depth DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION,
    perfo_type TEXT,
    diameter TEXT,
    density DOUBLE PRECISION,
    shots DOUBLE PRECISION,
    observations TEXT,
    calage TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Custom Tool Types Table
CREATE TABLE IF NOT EXISTS public.custom_tool_types (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL UNIQUE,
    default_name TEXT NOT NULL,
    default_od TEXT DEFAULT '2''7/8',
    default_custom_type TEXT DEFAULT 'EU',
    default_min_id TEXT DEFAULT '',
    french_designation TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Well History Table
CREATE TABLE IF NOT EXISTS public.well_history (
    id TEXT PRIMARY KEY,
    well_id TEXT NOT NULL REFERENCES public.wells(id) ON DELETE CASCADE,
    folio TEXT NOT NULL,
    snapshot TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    edited_by TEXT,
    CONSTRAINT unique_well_folio UNIQUE(well_id, folio)
);

-- 8. Sync Meta Table
CREATE TABLE IF NOT EXISTS public.sync_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Enable Row Level Security (RLS) & Policies
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wells ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.casing_strings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tubing_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perforation_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_tool_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.well_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_meta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read/write access" ON public.employees;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.wells;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.casing_strings;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.tubing_components;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.perforation_zones;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.custom_tool_types;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.well_history;
DROP POLICY IF EXISTS "Allow public read/write access" ON public.sync_meta;

CREATE POLICY "Allow public read/write access" ON public.employees FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.wells FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.casing_strings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.tubing_components FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.perforation_zones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.custom_tool_types FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.well_history FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write access" ON public.sync_meta FOR ALL USING (true) WITH CHECK (true);

-- DATA INSERTS
-- Data for employees (1 rows)
INSERT INTO public.employees (id, matricule, nom_prenom, role, password, service, fonction, personnel, observation, created_at) VALUES (1, '001', 'OULEDHAIMOUDA Abdelhalim', 'owner', '1234', 'Direction', 'Administrateur', NULL, NULL, '2026-07-26 02:54:47') ON CONFLICT (id) DO UPDATE SET matricule=EXCLUDED.matricule;

-- Data for wells (2 rows)
INSERT INTO public.wells (id, name, purpose, completion_type, reservoir, field, elevation_sol, elevation_forage, elevation_production, spool_prod, packer_type, susp_tbg, etan_tbg, origine_cotes, xmas_tree_brand, xmas_tree_type, xmas_tree_ract_sup, xmas_tree_pressure, xmas_tree_attache_tbg, xmas_tree_embase, xmas_tree_reduction, xmas_tree_olive, vannes_sas_marque, vannes_sas_nombre, vannes_sas_serie, vannes_maitresse_marque, vannes_maitresse_nombre, vannes_maitresse_serie, vannes_lat_tbg_marque, vannes_lat_tbg_nombre, vannes_lat_tbg_serie, vannes_lat_csg_marque, vannes_lat_csg_nombre, vannes_lat_csg_serie, observations, folio, folio_to_cancel, prod_tbg_od, prod_tbg_grade, prod_tbg_weight, updated_date, end_operation_date, vu_by, created_at, updated_at) VALUES ('well-1783519376578', 'RCL24', 'PPG', 'COMPLETION SIMPLE', 'F6', 'RCL', 628.83, 636.49, 628.85, '0.70', '', 'Tbg', '', '', '', '', '', '', 'OLIVE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '03', '02', '4"1/2', 'C85', '13.5', '2026-07-10', '', '', '2026-07-27 16:49:48', '2026-07-27 16:49:48') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;
INSERT INTO public.wells (id, name, purpose, completion_type, reservoir, field, elevation_sol, elevation_forage, elevation_production, spool_prod, packer_type, susp_tbg, etan_tbg, origine_cotes, xmas_tree_brand, xmas_tree_type, xmas_tree_ract_sup, xmas_tree_pressure, xmas_tree_attache_tbg, xmas_tree_embase, xmas_tree_reduction, xmas_tree_olive, vannes_sas_marque, vannes_sas_nombre, vannes_sas_serie, vannes_maitresse_marque, vannes_maitresse_nombre, vannes_maitresse_serie, vannes_lat_tbg_marque, vannes_lat_tbg_nombre, vannes_lat_tbg_serie, vannes_lat_csg_marque, vannes_lat_csg_nombre, vannes_lat_csg_serie, observations, folio, folio_to_cancel, prod_tbg_od, prod_tbg_grade, prod_tbg_weight, updated_date, end_operation_date, vu_by, created_at, updated_at) VALUES ('well-1782891613028', 'TG 64', 'PPH', 'COMPLETION SIMPLE', 'F2', 'TIGUENTOURINE', 497.3, 505.06, 497.3, '0.68', '//', 'Tbgg', '//', '', 'CAMERON', 'TCM-ET', '5" ACME-2G QUICK UNION ', '2000', 'Olive', '', '7’’1/16.2000 X 2’’9/16.2000', 'CAM A403 Taraudée en 2’’ 7/8  EU', 'CAMERON', '01', '2’’1/16.2000', 'CAMERON', '02', '2’’1/16.2000', 'CAMERON', '02', '2’’1/16.2000', 'CAMERON', '02', '2’’1/16.2000', '<p>PEA 13’’3/8* 9’’5/8 =450 psi</p>', '07', '06', '', '', '', '2026-07-18', '2018-01-10', 'L.BELHADJ', '2026-07-27 16:49:48', '2026-07-27 16:49:48') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;

-- Data for casing_strings (8 rows)
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('casing-1783616807189', 'well-1783519376578', 'Casing String', '26"', '18"5/8', 0.0, 90.36, 99.0, NULL, NULL, NULL, '', 0.0, '', '', 1, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('casing-1783616935468', 'well-1783519376578', 'Casing String', '16"', '13"3/8', 0.0, 835.36, 836.36, NULL, NULL, NULL, '', 54.0, '', '', 2, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('casing-1783617153566', 'well-1783519376578', 'Casing String', '12"', '9"5/8', 0.0, 1399.36, 1400.0, NULL, NULL, NULL, '', 47.0, '', '', 3, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('casing-1783617228937', 'well-1783519376578', 'Casing String', '8"1/2', '7"', 0.0, 1771.36, 1771.36, 1199.36, NULL, NULL, '', 32.0, '', '', 4, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('c-1782891663354-0', 'well-1782891613028', '18 5/8" Casing', '26', '18.625', 0.0, 41.0, 45.0, NULL, NULL, NULL, 'K55BTC', 87.5, '', '', 1, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('c-1782891663354-1', 'well-1782891613028', '13 3/8" Casing', '16', '13.375', 0.0, 333.0, 334.0, NULL, NULL, NULL, 'K55 BTC', 54.5, '', '', 2, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('c-1782891663354-2', 'well-1782891613028', '9 5/8" Casing', '12.25', '9.625', 0.0, 1057.0, 1059.0, NULL, NULL, NULL, 'P110 N/VAM', 47.0, '', '', 3, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.casing_strings (id, well_id, name, borehole_size, casing_size, top_depth, shoe_depth, drilled_depth, top_of_cement, top_of_liner, top_of_fonde, grade, weight, connection, observations, display_order, created_at, updated_at) VALUES ('c-1782891663354-3', 'well-1782891613028', '7" Casing', '8.5', '7', 0.0, 1129.0, 1130.0, NULL, NULL, NULL, 'P110 N-VAM', 29.0, '', '', 4, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;

-- Data for tubing_components (35 rows)
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617453212', 'well-1783519376578', 'Sabot', 'Shoe', '4"1/2', 0.3, 1598.23, TRUE, '', '01', 'N-VAM', '', 1, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617512152', 'well-1783519376578', 'F.Coupling', 'Other', '4"1/2', 1.69, 0.0, FALSE, '', '01', 'N-VAM	', '', 2, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617570859', 'well-1783519376578', 'Siège', 'Seating Nipple', '4"1/2', 0.37, 1596.24, TRUE, '', '01', 'X', '', 3, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617627270', 'well-1783519376578', 'F.Coupling', 'Other', '4"1/2', 1.69, 0.0, FALSE, '', '01', 'WC-FC', '', 4, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617666877', 'well-1783519376578', 'Tubing', 'Tubing', '4"1/2', 10.18, 0.0, FALSE, '', '01', 'WC-FC', '', 5, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617716411', 'well-1783519376578', 'Packer', 'Packer', '7"', 1.3, 1583.4, TRUE, '', '01', 'WCSOE', '', 6, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617791653', 'well-1783519376578', 'Anchor-seal', 'Anchor-seal', '4"1/2', 0.25, 0.0, FALSE, '', '01', 'WC-ALA', '', 7, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617824153', 'well-1783519376578', 'Tubing', 'Tubing', '4"1/2', 10.2, 0.0, FALSE, '', '01', 'EU', '', 8, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617866763', 'well-1783519376578', 'F.Coupling', 'Other', '4"1/2', 1.69, 0.0, FALSE, '', '01', 'N-VAM', '', 9, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617923369', 'well-1783519376578', 'Siège', 'Seating Nipple', '4"1/2', 0.37, 1570.56, TRUE, '', '01', 'X', '', 10, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783646910566', 'well-1783519376578', 'F.Coupling', 'Other', '4"1/2', 1.69, 0.0, FALSE, '', '01', 'N-VAM', '', 11, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783617962597', 'well-1783519376578', 'Tubing', 'Tubing', '//', 1568.84, 0.0, FALSE, '', '154', 'EU', '', 12, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1783618018964', 'well-1783519376578', 'Olive', 'Other', '7"1/16', 0.36, 0.0, FALSE, '', '01', '	N-VAM', '', 13, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896240333', 'well-1782891613028', 'Sabot ', 'Shoe', '2"3/8', 0.11, 1077.0, TRUE, ' MANCHON 2’’ 3/8  NU ', '01', 'NU', '', 1, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896306275', 'well-1782891613028', 'Siège', 'Other', '//', 0.49, 1076.89, TRUE, 'CAMCO– Bore 1”81', '01', 'D', '', 2, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896364203', 'well-1782891613028', 'Réduction', 'Reduction', '', 0.17, 0.0, FALSE, '2’’3/8NUMx2’’3/8EUM', '01', 'EU', '', 3, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896404844', 'well-1782891613028', 'tubing court', 'Tubing', '', 1.09, 0.0, FALSE, 'RI -J55 – 4.70# ', '01', 'EU', '', 4, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896445804', 'well-1782891613028', 'Packer', 'Packer', '7"', 0.7, 1074.79, TRUE, 'Haliburton size 23-32# H =0.35  B = 0.35', '01', 'AWS', '', 5, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782896542524', 'well-1782891613028', 'Anchor-seal', 'Anchor-seal', '2"3/8', 0.22, 0.0, FALSE, 'Haliburton-Ratch Latch', '01', 'EU', '', 6, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782917895446', 'well-1782891613028', 'Tubing', 'Tubing', '2"3/8', 9.6, 996.34, FALSE, 'RII -J55– 4.70 #', '01', 'EU', '', 7, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782917985629', 'well-1782891613028', 'Mandrin', 'Other', '2''''7/8', 1.98, 1064.62, TRUE, 'Weatherford', '01', 'SMO-1', '', 8, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918033965', 'well-1782891613028', 'Tubing', 'Tubing', '', 269.0, 1333.62, FALSE, 'RII -J55– 4.70 #', '28', 'EU', '', 9, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918421879', 'well-1782891613028', 'Mandrin', 'Other', '2''''7/8', 1.98, 793.64, TRUE, 'Weatherford', '01', 'SMO-1', '', 10, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918479927', 'well-1782891613028', 'Tubing', 'Tubing', '', 297.75, 1091.39, FALSE, 'RII -J55– 4.70 #', '31', 'EU', '', 11, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918556688', 'well-1782891613028', 'Mandrin ', 'Other', '', 1.98, 493.91, TRUE, 'Weatherford', '01', 'SMO-1', '', 12, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918609263', 'well-1782891613028', 'Tubing', 'Tubing', '', 480.02, 973.93, FALSE, 'RII -J55– 4.70 #', '50', 'EU', '', 13, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918646654', 'well-1782891613028', 'Tbg court', 'Tubing', '', 4.95, 978.88, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 14, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918679518', 'well-1782891613028', 'Tbg court', 'Tubing', '', 2.94, 981.82, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 15, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918716390', 'well-1782891613028', 'Tbg court', 'Tubing', '', 1.02, 982.84, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 16, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918737286', 'well-1782891613028', 'Tbg court', 'Tubing', '', 1.02, 983.86, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 17, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918755262', 'well-1782891613028', 'Tbg court', 'Tubing', '', 1.02, 984.88, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 18, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918774791', 'well-1782891613028', 'Tbg court', 'Tubing', '', 0.84, 985.72, FALSE, 'RI -J55 – 4.70#', '01', 'EU', '', 19, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918805447', 'well-1782891613028', 'Reduction', 'Reduction', '2''''7/8', 0.28, 986.0, FALSE, '2’’3/8EUFx2’’7/8EUF', '01', 'EU', '', 20, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918855054', 'well-1782891613028', 'Tbg court', 'Tubing', '2’’7/8', 0.36, 986.36, FALSE, 'RI -J55 – 6.50 #', '01', 'EU', '', 21, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;
INSERT INTO public.tubing_components (id, well_id, name, type, od, length, bottom_depth, is_cote_product_added, observations, qty, custom_type, min_id, display_order, created_at, updated_at) VALUES ('tubing-1782918892551', 'well-1782891613028', 'Olive', 'Other', '7’’1/16', 0.16, 986.52, FALSE, 'CAM  A403 ', '01', 'EU', '', 22, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;

-- Data for perforation_zones (1 rows)
INSERT INTO public.perforation_zones (id, well_id, top_depth, bottom_depth, height, perfo_type, diameter, density, shots, observations, calage, display_order, created_at, updated_at) VALUES ('perf-1782897635555', 'well-1782891613028', 1100.24, 1102.24, 2.0, 'CC', '4"1/2', 13.0, 26.0, '', 'CCL', 1, '2026-07-27 16:50:02', '2026-07-27 16:50:02') ON CONFLICT (id) DO UPDATE SET well_id=EXCLUDED.well_id;

